name: Daily Security Pipeline

on:
  schedule:
    - cron: '0 2 * * *'  # Every day at 2 AM UTC
  workflow_dispatch:      # Manual trigger for testing

jobs:
  dependencies-analysis:
    name: Dependencies Analysis
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Run OSV Scanner
        uses: google/osv-scanner-action@v1

      - name: Upload SARIF report to Security Dashboard
        uses: github/codeql-action/upload-sarif@v2
        with:
          sarif_file: results.sarif  # Replace with actual SARIF output path from OSV Scanner

  source-code-analysis:
    name: Source Code Analysis
    runs-on: ubuntu-latest
    container:
      image: returntocorp/semgrep

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Run Semgrep (Java ruleset)
        run: semgrep --config=p/java --sarif --output=semgrep-results.sarif

      - name: Upload SARIF report to Security Dashboard
        uses: github/codeql-action/upload-sarif@v2
        with:
          sarif_file: semgrep-results.sarif
  daily-dependency-scan:
    name: Daily Dependency Scan (Container)
    runs-on: ubuntu-latest
    container:
      image: ghcr.io/google/osv-scanner:latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Run OSV Scanner
        run: osv-scanner --lockfile=path/to/lockfile > osv-results.sarif

      - name: Upload SARIF to Security Dashboard
        uses: github/codeql-action/upload-sarif@v2
        with:
          sarif_file: osv-results.sarif

